### ISSUE TITLE
references to local files

### ISSUE THREAD

**Issue by kvernNC** [nexustar/scrcpy-flatpak#1]
Hi,
trying your flatpak method, as I don't like java app so much and I prefer it to be contained and easy removable.

Could you correct your com.Genymobile.Scrcpy.json, to remove local reference:
```

Downloading file:///home/uu/Downloads/ffmpeg-4.1.1.tar.xz
Failed to download sources: module ffmpeg: Couldn't open file /home/uu/Downloads/ffmpeg-4.1.1.tar.xz
```
Thanks

**Comment by nexustar** [comment]
have updated

**Comment by kvernNC** [comment]
A another little issue in README:
`flatpak --user install tutorial-repo com.Genymobile.Scrcpy.json`

should be: 
`flatpak --user install tutorial-repo com.Genymobile.Scrcpy`

Thanks for the flatpak, il works greats
